export const JEDI_FETCH_REQUEST = 'FETCH_REQUEST'
export const JEDI_FETCH_SUCCESS = 'FETCH_SUCCESS'
export const JEDI_FETCH_ERROR = 'FETCH_ERROR'

export const JEDI_ADD_REQUEST = 'ADD_REQUEST'
export const JEDI_ADD_SUCCESS = 'ADD_SUCCESS'
export const JEDI_ADD_ERROR = 'ADD_ERROR'

export default {
  JEDI_FETCH_REQUEST,
  JEDI_FETCH_SUCCESS,
  JEDI_FETCH_ERROR,
  JEDI_ADD_REQUEST,
  JEDI_ADD_SUCCESS,
  JEDI_ADD_ERROR
}
