export const JEDI_FETCH_REQUEST = 'FETCH_REQUEST'
export const JEDI_FETCH_SUCCESS = 'FETCH_SUCCESS'
export const JEDI_FETCH_ERROR = 'FETCH_ERROR'

export default {
  JEDI_FETCH_REQUEST,
  JEDI_FETCH_SUCCESS,
  JEDI_FETCH_ERROR
}
